# Generated by Django 6.0.1 on 2026-02-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience_required",
            field=models.CharField(
                blank=True,
                help_text="Years of experience required",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(
                blank=True, help_text="Salary range or amount", max_length=10, null=True
            ),
        ),
    ]
