# Generated by Django 5.0.14 on 2026-02-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_experience_required_alter_job_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience_required",
            field=models.CharField(
                blank=True,
                help_text="Years of experience required",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(
                blank=True,
                help_text="Salary range or amount",
                max_length=100,
                null=True,
            ),
        ),
    ]
