# Generated by Django 5.0.14 on 2026-02-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_skill_alter_jobseekerprofile_experience_and_more"),
        ("jobs", "0004_alter_job_experience_required_alter_job_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="skills_required",
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="accounts.skill"
            ),
        ),
    ]
