# Generated by Django 5.0.14 on 2026-02-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_job_skills_required_job_skills_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("REMOTE", "Remote"),
                    ("INTERNSHIP", "Internship"),
                ],
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("EXPIRED", "Expired"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="FavoriteJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job")},
            },
        ),
    ]
