# Generated by Django 5.0.14 on 2026-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_job_type_job_status_favoritejob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience_required",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Years of experience required",
                null=True,
            ),
        ),
    ]
