# Generated by Django 6.0.1 on 2026-02-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_job_experience_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="job_type",
        ),
        migrations.RemoveField(
            model_name="job",
            name="status",
        ),
        migrations.RemoveField(
            model_name="job",
            name="skills_required",
        ),
        migrations.DeleteModel(
            name="FavoriteJob",
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
