# Generated by Django 6.0.1 on 2026-02-08 04:11

import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_remove_job_job_type_remove_job_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                default=1,
                upload_to="resumes/",
                validators=[jobs.validators.validate_resume],
            ),
            preserve_default=False,
        ),
    ]
