# Generated by Django 6.0.1 on 2026-02-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_industry_jobcategory_job_industry_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                    ("FREELANCE", "Freelance"),
                    ("TEMPORARY", "Temporary"),
                ],
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="work_location_type",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ONSITE",
                max_length=20,
            ),
        ),
    ]
