# Generated by Django 6.0.1 on 2026-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_job_type_job_work_location_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary",
        ),
        migrations.AddField(
            model_name="job",
            name="salary_display",
            field=models.CharField(
                blank=True,
                help_text="Display text for salary (e.g., '$50k-$70k')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum salary (annual)", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.PositiveIntegerField(
                blank=True, help_text="Minimum salary (annual)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                    ("FREELANCE", "Freelance"),
                    ("TEMPORARY", "Temporary"),
                ],
                db_index=True,
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="job",
            name="work_location_type",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                db_index=True,
                default="ONSITE",
                max_length=20,
            ),
        ),
    ]
