# Generated by Django 6.0.1 on 2026-02-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_jobseekerprofile_skills_delete_skill_and_more"),
        ("jobs", "0012_alter_job_options_remove_job_salary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to="accounts.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
                "unique_together": {("job_seeker", "job")},
            },
        ),
    ]
