# Generated by Django 6.0.1 on 2026-02-09 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_jobseekerprofile_skills_delete_skill_and_more"),
        ("jobs", "0014_emailnotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailnotification",
            options={},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={},
        ),
        migrations.AlterModelOptions(
            name="savedjob",
            options={},
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="job_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.jobapplication",
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("APPLICATION_ACCEPTED", "Application Accepted"),
                    ("APPLICATION_REJECTED", "Application Rejected"),
                    ("NEW_MESSAGE", "New Message"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="accounts.employerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_required",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of experience required"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                    ("FREELANCE", "Freelance"),
                    ("TEMPORARY", "Temporary"),
                ],
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_display",
            field=models.CharField(
                blank=True,
                help_text="How salary is displayed (e.g., 'Negotiable', '$50k-80k')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum salary", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_min",
            field=models.PositiveIntegerField(
                blank=True, help_text="Minimum salary", null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills_required",
            field=models.TextField(help_text="Comma-separated skills"),
        ),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="work_location_type",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ONSITE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_thread",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="message_threads", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="jobs.messagethread",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
