# Generated by Django 6.0.1 on 2026-02-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_emailnotification_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='job_application',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_thread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='job_application',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='participants',
        ),
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageThread',
        ),
    ]
