# Generated by Django 6.0.1 on 2026-02-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("JOB_SEEKER", "Job Seeker"),
                    ("EMPLOYER", "Employer"),
                ],
                default="JOB_SEEKER",
                max_length=20,
            ),
        ),
    ]
