# Generated by Django 6.0.1 on 2026-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_role_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
