# Generated by Django 6.0.1 on 2026-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employerprofile_jobseekerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("JOB_SEEKER", "Job Seeker"), ("EMPLOYER", "Employer")],
                max_length=20,
            ),
        ),
    ]
