# Generated by Django 5.0.14 on 2026-02-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_role_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="experience",
            field=models.CharField(
                blank=True, help_text="Years of experience", max_length=5, null=True
            ),
        ),
    ]
