# Generated by Django 5.0.14 on 2026-02-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_jobseekerprofile_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="experience",
            field=models.CharField(
                blank=True, help_text="Years of experience", max_length=5, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="job_seekers", to="accounts.skill"
            ),
        ),
    ]
