# Generated by Django 6.0.1 on 2026-02-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_skill_alter_jobseekerprofile_experience_and_more"),
        ("jobs", "0008_remove_job_job_type_remove_job_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
